apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: x87bterdu-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/tnevrlka-rhtap/rhtap-qe-go:cdba262d7a6a7ba95523b21a06eedd3103692fc2@sha256:df29a1c3896254302a05a7e4dff34bc92d383272d73c02b84e2435c5413e012b
          name: container-image
